server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sofka
    username: postgres
    password: Passw0rd.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/