server:
  port: 8081
spring:
  application:
    name: ms-customers
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: Passw0rd.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      title: Customer API
      description: API para gestionar clientes
      version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/